version: '3.8'
services:
  main:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 9191:8000
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: laravel
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 3306:3306